### PR TITLE
Add support for templates folder when packaging helm (#69)

### PR DESCRIPTION
**Pull request by iDiogenes**
It can be necessary in bazel to assemble template files together into a single directory to be packaged by using something like aspect's `copy_to_directory`. This commit updates the package.go to  include support for path to a templates directory which would be generated by `copy_to_directory`.

### CODE REVIEW

**Comment by iDiogenes** [comment]
Looks like the test that are failing are the docs_diff_test. The issue here is not clear to me, so if possible could someone who understands what needs to be done to get the docs test passed please address.

**Comment by iDiogenes** [comment]
@abrisco or @freeformstu - I have been currently pulling this code directly from my repo as I need the functionality, but would prefer to use the bazel central registry again for this module. Would it be possible for someone to review this PR and provide feedback.  Thank you.

**Comment by abrisco** [comment]
Hey! Super sorry about the absence here! I will take a look this week :)

**Review by abrisco — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
